<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-06 05:54
=======
# Generated by Django 5.0.1 on 2024-02-09 05:05
>>>>>>> main

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
<<<<<<< HEAD
                ('begining_date', models.DateTimeField()),
                ('branch', models.CharField(default='CME', max_length=5)),
                ('ending_date', models.DateTimeField()),
=======
>>>>>>> main
                ('sem', models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM')], max_length=10, primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Unit1marks',
=======
            name='Students',
            fields=[
                ('pin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(default='student', max_length=20)),
                ('fname', models.CharField(default='father', max_length=20)),
                ('mname', models.CharField(default='mother', max_length=20)),
                ('phno', models.CharField(default='123456', max_length=12)),
                ('fphno', models.CharField(default='123445654', max_length=12)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('category', models.CharField(default='category', max_length=5)),
                ('scategory', models.CharField(default='subcategory', max_length=10)),
                ('religion', models.CharField(default='religion', max_length=20)),
                ('sacno', models.CharField(default='1111', max_length=20)),
                ('sifsc', models.CharField(default='1234', max_length=20)),
                ('sbranch', models.CharField(default='CME', max_length=20)),
                ('macno', models.CharField(default='1234', max_length=22)),
                ('mifsc', models.CharField(default='ifsc', max_length=20)),
                ('mbranch', models.CharField(default='motherac', max_length=20)),
                ('email', models.CharField(default='@gmail.com', max_length=30)),
                ('sscrank', models.IntegerField(default=1234)),
                ('sschallticketno', models.CharField(default='123456', max_length=20)),
                ('address', models.CharField(default='address', max_length=30)),
                ('village', models.CharField(default='village', max_length=20)),
                ('mandal', models.CharField(default='mandal', max_length=20)),
                ('dist', models.CharField(default='district', max_length=20)),
                ('allotedcategory', models.CharField(default='general', max_length=20)),
                ('dateofjoining', models.DateTimeField(blank=True, null=True)),
                ('polycetrank', models.IntegerField(default=1234)),
                ('polycetno', models.IntegerField(default=1234)),
                ('aadharno', models.CharField(default='111111111111', max_length=22)),
                ('rationno', models.CharField(default='1234', max_length=20)),
                ('tcno', models.IntegerField(default='1234')),
                ('discontinueddate', models.DateTimeField(blank=True, null=True)),
                ('odno', models.IntegerField(default='1234')),
                ('odissueddate', models.DateTimeField(blank=True, null=True)),
                ('tcissueddate', models.DateTimeField(blank=True, null=True)),
                ('studycertificateissueddate', models.DateTimeField(blank=True, null=True)),
                ('studentimage', models.ImageField(blank=True, null=True, upload_to='static/Images/student_image/', verbose_name='Title Image')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
>>>>>>> main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20)),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Teacher'), (2, 'Student')], default=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('pin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=20)),
                ('mandal', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=12)),
                ('fphno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateTimeField(default='2020-1-1')),
                ('gender', models.CharField(max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('nfw', models.IntegerField()),
                ('npd', models.IntegerField()),
                ('twd', models.IntegerField()),
                ('tpd', models.IntegerField()),
                ('per', models.IntegerField()),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
            ],
        ),
        migrations.CreateModel(
            name='Unit1marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Unit2marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Unit3marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
    ]
