# Generated by Django 5.0 on 2024-01-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=20)),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('sem', models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM')], max_length=10, primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('pin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=20)),
                ('mandal', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=12)),
                ('fphno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateTimeField(default='2020-1-1')),
                ('gender', models.CharField(max_length=1)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='static/Images/student_image/', verbose_name='Title Image')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('nfw', models.IntegerField()),
                ('npd', models.IntegerField()),
                ('twd', models.IntegerField()),
                ('tpd', models.IntegerField()),
                ('per', models.IntegerField()),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
            ],
        ),
        migrations.CreateModel(
            name='Unit1marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
    ]
