# Generated by Django 5.0 on 2024-01-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=20)),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('pin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=20)),
                ('mandal', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=12)),
                ('fphno', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Unit1marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=20)),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('nfw', models.IntegerField()),
                ('npd', models.IntegerField()),
                ('twd', models.IntegerField()),
                ('tpd', models.IntegerField()),
                ('per', models.IntegerField()),
                ('pin', models.ForeignKey(db_column='pin', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
            ],
        ),
    ]
