# Generated by Django 5.0 on 2024-01-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_image',
            new_name='studentimage',
        ),
    ]
