# Generated by Django 5.0.1 on 2024-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='studycertificateissudedate',
        ),
        migrations.RemoveField(
            model_name='students',
            name='tcissudedate',
        ),
        migrations.AddField(
            model_name='students',
            name='studycertificateissueddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='tcissueddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
