# Generated by Django 5.0.1 on 2024-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='begining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='ending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
