# Generated by Django 5.0 on 2024-01-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit1marks',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='unit1marks',
            name='semister',
        ),
        migrations.AddField(
            model_name='unit1marks',
            name='student',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students'),
        ),
        migrations.AddField(
            model_name='unit1marks',
            name='studentclass',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateTimeField(default='2020-1-1'),
        ),
    ]
