# Generated by Django 5.0 on 2024-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit1marks',
            name='sem',
            field=models.CharField(default='3SEM', max_length=20),
            preserve_default=False,
        ),
    ]
