# Generated by Django 5.0 on 2024-01-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0002_rename_student_image_students_studentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit2marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Unit3marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
                ('s6', models.IntegerField()),
                ('s7', models.IntegerField()),
                ('s8', models.IntegerField()),
                ('s9', models.IntegerField()),
                ('s10', models.IntegerField()),
                ('s11', models.IntegerField()),
                ('s12', models.IntegerField()),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
                ('studentclass', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.studentclass')),
            ],
        ),
    ]
