# Generated by Django 5.0.1 on 2024-02-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0002_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='aadharno',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='allotedcategory',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='dist',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='fphno',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='macno',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mandal',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mbranch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mifsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='odno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phno',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='polycetno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='polycetrank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='rationno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sacno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sbranch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='scategory',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sifsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sschallticketno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='tcno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='village',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
