# Generated by Django 5.0 on 2024-03-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0002_unit1marks_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit2marks',
            name='studentclass',
        ),
    ]
