# Generated by Django 5.0 on 2024-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0003_remove_unit2marks_studentclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit1marks',
            name='studentclass',
        ),
        migrations.AddField(
            model_name='unit2marks',
            name='sem',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
