# Generated by Django 5.0 on 2024-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0004_remove_unit1marks_studentclass_unit2marks_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit3marks',
            name='studentclass',
        ),
        migrations.AddField(
            model_name='unit3marks',
            name='sem',
            field=models.CharField(default='1YEAR', max_length=10),
            preserve_default=False,
        ),
    ]
