# Generated by Django 5.0.1 on 2024-02-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0004_alter_students_aadharno_alter_students_dateofjoining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='discontinueddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='polycetno',
            field=models.IntegerField(default=1234),
        ),
    ]
