# Generated by Django 5.0.1 on 2024-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0004_students_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sem',
            field=models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM')], max_length=20, null=True),
        ),
    ]
