# Generated by Django 5.0 on 2024-03-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0005_remove_unit3marks_studentclass_unit3marks_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit1marks',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit1marks',
            name='s9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit2marks',
            name='s9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit3marks',
            name='s9',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UnitMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default='UNIT1', max_length=20)),
                ('sem', models.CharField(max_length=20)),
                ('s1', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('s5', models.IntegerField(default=0)),
                ('s6', models.IntegerField(default=0)),
                ('s7', models.IntegerField(default=0)),
                ('s8', models.IntegerField(default=0)),
                ('s9', models.IntegerField(default=0)),
                ('s10', models.IntegerField(default=0)),
                ('s11', models.IntegerField(default=0)),
                ('s12', models.IntegerField(default=0)),
                ('student', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='mbts.students')),
            ],
        ),
    ]
