# Generated by Django 5.0 on 2024-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0005_alter_students_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='sem',
            field=models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM'), ('COMPLETED', 'COMPLETED'), ('DETAINED', 'DETAINED')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='aadharno',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='allotedcategory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='dist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='macno',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mandal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mbranch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='odno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='polycetno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='polycetrank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='rationno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='religion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sacno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sbranch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='scategory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem',
            field=models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM'), ('COMPLETED', 'COMPLETED'), ('DETAINED', 'DETAINED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sschallticketno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sscrank',
            field=models.IntegerField(blank=True, default=1234, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='tcno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='village',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
