# Generated by Django 5.0 on 2024-02-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0006_alter_studentclass_sem_alter_students_aadharno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fname',
            field=models.CharField(default='father', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='mname',
            field=models.CharField(default='mother', max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem',
            field=models.CharField(choices=[('1YEAR', '1 YEAR'), ('3SEM', '3 SEM'), ('4SEM', '4 SEM'), ('5SEM', '5 SEM'), ('6SEM', '6 SEM'), ('COMPLETED', 'COMPLETED'), ('DETAINED', 'DETAINED')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='sname',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
