# Generated by Django 5.0 on 2024-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbts', '0008_marks_s10e_marks_s10i_marks_s10s_marks_s10t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='studentclass',
        ),
        migrations.AddField(
            model_name='marks',
            name='sem',
            field=models.CharField(default='1YEAR', max_length=5),
            preserve_default=False,
        ),
    ]
